services:
  ctfd:
    image: ctfd/ctfd:latest
    user: root
    restart: always
    env_file: .env
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - mariadb
    networks:
      - default

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ctfd
      - transcendence
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - default

  mariadb:
    image: mariadb:10.11
    restart: always
    env_file: .env
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - default
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
      - default

  transcendence_db:
    image: postgres
    container_name: transcendence_db
    env_file: .env
    volumes:
      - ./data/transcendence_db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default

  transcendence:
    container_name: transcendence
    build:
      context: ./transcendence
      dockerfile: Dockerfile
    depends_on:
      - transcendence_db
    env_file: .env
    volumes:
      - ./transcendence:/transcendence
    restart: unless-stopped
    networks:
      - default

  django:
    build: ./django
    ports:
      - "6001:80"
    networks:
      - default

  programming:
    build: ./programming
    ports:
      - "6002:80"
    networks:
      - default

volumes:
  db_data:

networks:
  default:
